### ISSUE TITLE
csvs open in safari on certain machines

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#118]
HHMI says: 
"Mark reported yesterday that in Safari, the spreadsheet opened in a browser window and he had to copy and paste it into excel. I couldn’t test with Safari today because I am just seeing a blank white screen when I go to the site on Safari (the same happens with IE on a PC)."

Not sure if this is an OS or browser-specific issue?

**Comment by shaunanoordin** [comment]
This has been partially fixed by #124, in that CSVs are now properly downloaded as CSV files instead of opening as a test in a new browser window.

However, if a user's computer is set to open CSVs in Safari (?!), then that's computer-specific and we can't really apply a fix to that.

Jim did have a helpful suggestion of adding a `Content-Disposition` to the response headers, but that solution will need to be implemented at a more server-level instead of at the React-app level.

For now, I'm closing this issue and exploring if #105 would be a better solution to keep our general users happy.

**Comment by chrislintott** [comment]
Maybe we should add a note somewhere saying that you should make sure you’re downloading and not opening a CSV?

C
