### ISSUE TITLE
Teacher / student routes need to be authenticated

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/wildcam-gorongosa-education#26]
If you're not logged in, you should be required to authenticate before accessing those routes. Related to #21

**Comment by shaunanoordin** [comment]
Here are some thoughts about Authentication, in relation to WGE Issue #26:

1: When an unautheticated user tries to access the /teachers (or /students) page, they will instead go to a page that says: "To access our features as a Teacher, please login: [button]". This can be done, no worries.

2: When an authenticated user clicks the Logout button, she/he needs to be **booted back to the Home** page, is everyone in agreement with this?

3: What happens when an authenticated user has two windows open, but logs out of one? The correct behaviour is for the second window to boot the user back to the home page too (as the first window would)... but if this is the case, we run into the matter of needing an elegant way to **"check-every-second/every-render-if-user-is-logged"**. Any thoughts on this?

**Comment by rogerhutchings** [comment]
If we store the user in the redux state object, and have a listener on it, then it'll work in any window?

**Comment by shaunanoordin** [comment]
Thanks @rogerhutchings , looks like redux & listening for the state update is the way to go.

I created a functional branch where I made the Panoptes client check user state in index.jsx and allowed/disallowed paths depending on user-login-state, but the darn thing wouldn't give a flying fart when the user clicked logout.

Follow up question: I recall you experimented with a method of URL-redirecting a user using react-router? I'd like to know if you found a good implementation for, e.g. bootUserTo('/home').
