### ISSUE TITLE
Add links to Wildcam FAQ and Blog on ed portal

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#83]
This will be easy. Where do we want them though?

**Comment by simoneduca** [comment]
@aliburchard would it make sense to have them under resources tab?

**Comment by aliburchard** [comment]
I'm thinking just make them top-level tabs that appear tot he right of classrooms/data/feedback for both students and teachers, and that open in a new tab (just like the classification interface will).

**Comment by simoneduca** [comment]
The tabs text will be messy with the Zoologo in the header. Shall I get rid of it then?

**Comment by aliburchard** [comment]
oh boo. You're right. yeahhhh go ahead and drop the logo, thanks.

**Comment by shaunanoordin** [comment]
A few points on what I plan to do:
- I'll shift/move the Zooniverse logo instead of getting rid of it completely
- The Blog link will be added to both Student and Teacher pages (and yep, it'll open a new window to http://blog.wildcamgorongosa.org/)
- However, I will **not** add the FAQ link, as I feel that it's too jarring to click the FAQ link on one page, then get directed to a _sub-page_ of _another site_. (https://www.wildcamgorongosa.org/#/about/faq) The Blog navigation is OK as users are used to logs being a separate entity, but FAQs should be of the site you're looking at, I feel.
